spring:
  application:
    name: snippetvault-api

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: snippetvault
    password: secret
    hikari:
      initialization-fail-timeout: 0

  flyway:
    locations: classpath:db/migrations
    oracle:
      sqlplus: true
    mixed: true
    connect-retries: 60
    connect-retries-interval: 2s

  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

jwt:
  secret: ZXhhbXBsZS1zZWNyZXQta2V5LXRvLWJlLXJlcGxhY2VkLXdpdGgtYS1sb25nZXItYW5kLXNlY3VyZXItb25l
  expiration: 36000000

app:
  frontend: http://localhost:5173
  admin-user: admin
  admin-password: password