spring:
  application:
    name: snippetvault-api

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: snippetvault
    password: secret

  flyway:
    locations: classpath:db/migrations