services:
  oracle:
    image: 'wnameless/oracle-xe-11g-r2'
    environment:
      - 'ORACLE_ALLOW_REMOTE=true'
    volumes:
      - './init/script.sh:/docker-entrypoint-initdb.d/script.sh'
      - 'oracle_data:/u01/app/oracle'
    ports:
      - '1521:1521'

volumes:
  oracle_data:
    driver: local